### PR TITLE
Adding more features for users to select profile pictures.

### PR DESCRIPTION
**Pull request by AleksandarMitevski**
Hello,

I was able to find and fix the problems from my last PR. It was some extra code that was added to the public/js/app.js and register.js in the same folder which i don't know how it happened. I also updated the branch to be in sync with the upstream master branch.

I also changed the error message that gets triggered when a user uploads a picture that exceeds 3MB to say maximum size is 2MB because when converting to base64 the image's file size increases by 4/3, so the file size shouldn't exceed 3MB if a user inputs a 2MB image.

Best Regards,
Aleksandar.

### CODE REVIEW

**Comment by thdebay** [comment]
Hello @AleksandarMitevski, good job, the photo roster looks good! I had a look at the code and I liked how you integrated your methods into the existing Backpack's architecture (CourseCrudController and buttons). I hope it was a productive task for you to discover Backpack. 

I'm having trouble to test the picture-taking part: I get the following error when I click on "take picture"

image

Uploading a picture file seems to work better, however I get a timeout when I visit the "/student" URL.

Have you also gotten these errors at some point during development? Maybe this is some configuration issue on my computer.

PS - don't worry if Github says your PR cannot be merged automatically. I'll take care of merging the conflicting files manually.

**Comment by AleksandarMitevski** [comment]
Thank you @thdebay , it definitely was a productive task. I learned a lot about Vue and Backpack because this is the first time i have worked with them.

I haven't gotten those errors while i was working on the features. I don't have a webcam for my pc nor a laptop to test the features with a built in device so i was testing it with manycam and droidcam linked to my phone and the picture capture worked, i don't know if that could be related to why i wasn't getting the errors. I have a laptop now, i'll test the site on there as soon as i'm able to.

Also i noticed i forgot to delete the console log and i forgot to add the visual representation of the files name when it gets selected.

**Comment by AleksandarMitevski** [comment]
Are you testing the site in a local environment?

**Comment by thdebay** [comment]
Yes, I'm using homestead on my local machine

**Comment by AleksandarMitevski** [comment]
I don't know if this is the issue since i don't know how homestead works but for MediaDevices to work on non local environment the site needs to have the Permissions-Policy HTTP Header but github doesn't include the vendor generated files and when the files get regenerated it doesn't include the **header()** method i included in the **showRegistrationForm()** method in **\Backpack\CRUD\app\Http\Controllers\Auth\RegisterController**

**Comment by thdebay** [comment]
Indeed, that's what you said in the other PR, I forgot about this. The vendor directory is excluded from version control because it will be re-generated when someone runs `composer install`. But we can publish the files we need to customize. Can you post the custom method here and I will try to see if this fixes the issue. If so, I'll show you how to integrate it

**Comment by AleksandarMitevski** [comment]
This is the method return of **showRegistrationForm()**

91669513-b9aa2e80-eb15-11ea-86ab-21cbabb1f044

**Comment by thdebay** [comment]
I'll have a final look at the rest of the branch and merge the PR. I'll let you know when this is done!

**Comment by AleksandarMitevski** [comment]
Oh damn i completely forgot about that part of the documentation, i'm sorry i didn't mention it. 

Thanks, if any changes need to be done i'll be happy to do them.

**Comment by thdebay** [comment]
@AleksandarMitevski your PR was merged in commit b83123ea2b02c9dbe5d96c1ae67b5a71ef2ff75c

Thanks for this job, this is much appreciated and I believe it is an important new feature to this software.

@all-contributors add @AleksandarMitevski for code

**Comment by AleksandarMitevski** [comment]
Thank you. I definitely improved my skills while working on these issues. If it isn't too much trouble could you tell me about some of the changes you made to my code and why, to help me improve my dev skills moving onwards. I saw the changes made to the roster view, it looks very cleaner and simpler unlike my ugly block of code lol.

**Comment by thdebay** [comment]
Actually, I didn't change much of your code. I cleaned some tiny bits like this one:
image
 but that was it, the rest was working so I didn't touch it.

The only thing I simplified is the roster. You had included a lot of student data in this view, but I think it's best to put the focus on the pictures and leave other details for the list view. More importantly, it allowed me to refactor your loop:

image

I would advise to use Blade's helpers (`@foreach... @endforeach`) instead of building native PHP loops like you did [here](https://github.com/AleksandarMitevski/academico/blob/04add274d02290b5b474ca8d851d054c478b2e84/resources/views/courses/components/rosterComponent.blade.php). This being said, your code was working fine, I just found it less readable than the Blade-only, simplified version.

Finally, we had this discussion about the header in `showRegistrationForm()`. It seems that everythings works fine on a clean install, so I didn't include it. The trick is to serve the app using HTTPS only, otherwise the webcam is not available.

I had to create a separate commit because, for some reason, your commit included files that already existed, like the `create_media_table` migration. I didn't want to confuse other users so I committed only the files relevant to the changes you made.

Please let me know if you have any questions or comments :)

**Comment by AleksandarMitevski** [comment]
Thank you for the feeback. 

I built the native PHP loops because i didn't know how to segment the data to 5 per row with @foreach but looking at your roster table it does it on its own. I'm guessing it starts printing to a new row because it runs out of room in the original row div if that makes sense? 

Yeah it's my fault i didn't mention the HTTPS requirement, it didn't cross my mind that it would cause trouble for local development since the docs stated it isn't needed for local, my bad.

**Comment by thdebay** [comment]
Correct; the rows are handled using a CSS grid. Backpack has its own CSS framework but most of it is based on Bootstrap. In this case, the [grid](https://getbootstrap.com/docs/4.0/layout/grid/) lets us specify the width of each card and breaks to a new line when there's no space left. There are 12 columns on the page, you just have to tell how wide (how many columns) each card should be. This system also allows to specify a different column width for mobile screens, if needed.

> Yeah it's my fault i didn't mention the HTTPS requirement, it didn't cross my mind that it would cause trouble for local development since the docs stated it isn't needed for local, my bad.
No worries 👌🏻

**Pull request closed without merging**
