### PR TITLE
274 convert hourly price to cents

### LINKED ISSUE #274: Convert hourly_price column to cents
To avoid rounding errors - especially within JS functions - all prices have been migrated to using cents.

The `hourly_price` in the course table is the last one remaining

### PR DESCRIPTION
**Pull request by MizouziE**
Hi,

I have converted price into cents in the same manner as the other price references, however I have a concern I would like to clarify before merging:

- if implemented, this will not function well with existing records, only new ones
- would it be required to convert existing records in the database or...
- rather use an if check against records `created_at` determining whether to convert output or not?

If you can let me know the preferred procedure I will be very happy to implement.

Closes #274 

Thanks

Sam

### CODE REVIEW

**Comment by thdebay** [comment]
Hello and thank you for your interest in the project. I think the best option is to convert existing records, using a simple SQL migration script. You're welcome to work on this issue if you'd like, and feel free to reach out to me if you need anything!

Best,

**Comment by MizouziE** [comment]
Thanks for pointing me in the right direction. I will work on the migration and push to this branch once complete and request your review.

**Comment by MizouziE** [comment]
Hi @thdebay,

All done and tested on my end. Giving desired results and no errors if column is empty.

Thanks again for the opportunity!

**Comment by thdebay** [comment]
I reviewed and tested, it works just fine. A warm thank-you for this PR @MizouziE!

**Comment by thdebay** [comment]
@all-contributors add @MizouziE for code,doc

**Comment by thdebay** [comment]
https://github.com/all-contributors add @MizouziE for code and doc

**Comment by thdebay** [comment]
@all-contributors add @MizouziE for code and doc

**Comment by MizouziE** [comment]
My pleasure! 🙏

**Pull request merged**
