### PR TITLE
Changes to test classes

### PR DESCRIPTION
**Pull request by AleksandarMitevski**
Hello, 
Since this is my first PR request i'm sure there will be changes that aren't done correctly or changes that i haven't written, but i'd be happy to spend time on fixing or adding whatever is needed.

### CODE REVIEW

**Comment by thdebay** [comment]
Hello @AleksandarMitevski  and thank you for this PR. I had a look at the tests you added and I think they work perfectly!

I will only change one thing after merging the PR: instead of the full DB seeder we can use "TestSeeder" which is a lot faster, since it only includes what's needed for tests and not sample data

Your contribution will be credited and your name will appear on the front page of the repository. I highly appreciate your effort to make this project better :+1:

**Comment by thdebay** [comment]
@all-contributors credit @AleksandarMitevski  for code

**Comment by thdebay** [comment]
@all-contributors add @AleksandarMitevski for test

**Comment by AleksandarMitevski** [comment]
Thank you for the compliment @thdebay, it means a lot. 

That was something that was bugging me when i was running the tests but i overlooked the DB seeder part because of my lack of knowledge. Now i know.

It was my pleasure to be able to contribute, it gave me a chance to work on a real world project! I'd like to work on some other issues in the near future.

**Pull request merged**
