### PR TITLE
Additional Contact deletion

### PR DESCRIPTION
**Pull request by Aybee5**

### CODE REVIEW

**Comment by laxsmi** [comment]
Thank you @Aybee5 for this PR. I'll look into it this week-end and let you know

**Comment by Aybee5** [comment]
Okay, thank you.

**Comment by laxsmi** [comment]
Hi @Aybee5 , I reviewed your PR. Everything looks good but the contact isn't removed from screen until a page refresh is performed. I haven't had time to look at it yet but I'll fix it and merge your commits soon. I'll keep you posted

**Comment by laxsmi** [comment]
The issue I mentionned could be fixed (by passing the index as a parameter with the method deleteContact(), but we still need a way to move to the "student info" tab after performing the deletion... As a temporary solution, and to merge your PR quickly, I forced a page reload after each each contact deletion.

Thanks @Aybee5 for this PR!

@all-contributes please add @Aybee5  for code

**Comment by laxsmi** [comment]
@all-contributors please add Aybee5 for code

**Pull request merged**
