### PR TITLE
Added profile picture selection and capture and roster view

### PR DESCRIPTION
**Pull request by AleksandarMitevski**
Hello, 

This being my second PR i expect to comeback and make changes because i probably missed something or didn't do something right which i would be happy to do. I look forwards to getting feedback.

I added the translations of the buttons in the 3 languages offered, but i used google translate for that and i'm not sure that they are completely correct.

### CODE REVIEW

**Comment by thdebay** [comment]
Hello, I will have a look and let you know quickly.

**Comment by AleksandarMitevski** [comment]
Thanks @thdebay ,
I closed the PR because this error appeared Git Error: You need to resolve your current index first. I'm having some trouble with the branches and syncing everything. When i fix everything i'll resubmit the PR.

**Comment by thdebay** [comment]
The screenshots look good, I can't wait to test it!

Maybe you need to rebase your branch on master in order to solve the git error?

However, if all the changes you wanted to include are here, it's okay to keep the PR as it is, I think I'll be able to merge it. I'll solve the conflicts if there are some

**Comment by AleksandarMitevski** [comment]
I nearly had a heart attack while tinkering with gitbash because it deleted all my changes and synced it with the upstream academico, but i downloaded the branch Manage-student-profile-picture branch with all the changes luckily.

I'll try to rebase the branch, hopefully it works. This branch is 19 commits behind the main one, wouldn't that cause any trouble ?

Also i noticed one more thing, the changes i made to the backpack RegisterController  showRegistrationForm method where i added the Permissions-Policy header disappeared because i believe git doesn't include the vendor file. For the getUserMedia to be able to ask the user for their attached media the page needs to have that header per the documentation, is there a way to configure backpack to generate that part?

**Pull request closed without merging**
